# Generated by Django 4.2.7 on 2023-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ANY_app1", "0002_person_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=40),
        ),
    ]
