# Generated by Django 4.2.7 on 2023-11-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ANY_app1", "0003_person_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_name", models.CharField(max_length=45)),
                ("description", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="images")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="ANY_app1.person",
                    ),
                ),
            ],
        ),
    ]
